defaults:
  - env: easy_box_small_basket
  - planner: llm_backtrack

# runner
runner: tamp

# trace size
planner:
  trace_size: 5

# max llm callls
max_llm_calls: 3

domain_name: kitchen

prob_num: [3, 4, 5, 6]
prob_idx: [1]
trial: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
repeat: [1, 2, 3]

# saved dir
save_dir: experiments/kitchen/saved_runs/run_tamp/${now:%Y-%m-%d-%H-%M-%S}/${env.env_name}_${planner.planner_prompt_file}_${planner.with_mp_feedback}

json_path: /home/minseo/robot_ws/src/tamp_llm/experiments/kitchen/problem/problems_meta_short.json

save_to_file: True
overwrite_instances: False

play_traj: True
use_gui: True

# disable hydra saving
hydra:
  output_subdir: null
  run:
    dir: ${save_dir}